export const ServiceCenterText = [
    { serviceName: '회원정보', serviceImg: 'service_member' },
    { serviceName: '메일', serviceImg: 'service_mail' },
    { serviceName: '카페', serviceImg: 'service_cafe' },
    { serviceName: '블로그', serviceImg: 'service_blog' },
    { serviceName: '지식인', serviceImg: 'service_kin' },
    { serviceName: 'VIBE', serviceImg: 'service_vibe' },
    { serviceName: '캘린더', serviceImg: 'service_calendar' },
    { serviceName: '쇼핑라이브', serviceImg: 'service_shoppinglive' },
    { serviceName: '웹툰', serviceImg: 'service_webtoon' },
    { serviceName: '지도', serviceImg: 'service_map' },
    { serviceName: '사전', serviceImg: 'service_dictionary' },
    { serviceName: '네이버플러스 멤버십', serviceImg: 'service_nmembership' },
    { serviceName: 'eXpert', serviceImg: 'service_expert' },
    { serviceName: '시리즈', serviceImg: 'service_series' },
    { serviceName: '애드포스트', serviceImg: 'service_adpost' },
    { serviceName: 'MYBOX', serviceImg: 'service_mybox' },
    { serviceName: '네이버 게임', serviceImg: 'service_navergame' },
    { serviceName: '스마트플레이스', serviceImg: 'service_smartplace' },
    { serviceName: '뉴스', serviceImg: 'service_news' },
    { serviceName: '네이버앱', serviceImg: 'service_naverapp' },
    { serviceName: 'NOW', serviceImg: 'service_now' },
    { serviceName: '포스트', serviceImg: 'service_post' },
    { serviceName: '네이버검색', serviceImg: 'service_search' },
    { serviceName: '인물정보', serviceImg: 'service_peopleinfo' },
];